config/routes.rb
Rails.application.routes.draw do
  resources :users
  get 'signup69' => 'signup#new'
  get 'home' => 'home#index'
  get 'welcome', to:'welcome#about', as:'about'

    root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor 
	has_secure_password
	validates :first_name,  presence: true, length: { maximum: 50 }, allow_blank: false
	validates :last_name,  presence: true, length: { maximum: 50 }, allow_blank: false
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }, allow_blank: false
    validates :team_id, presence: false, allow_blank: false
    before_save   :downcase_email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
	def new
		@user = User.new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :team_id, :password_digest)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		render :layout => true
	end

	def about
		render :layout => true
	end

	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/home/index.html.erb
<h2>Home Page</h2>
<p>
  The time is now: <%= Time.now %>
</p>
<%= image_tag "/assets/background-coach.png", alt: "Recruiter Image", id: "background-image" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recruitme</title>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container">
	
	<div id="top-navbar">
		<%= link_to (image_tag "TitleLogo.png", alt: "Title Image", id: "title-image"), root_path %>
			<ul id="menu-bar">
			<li><%= link_to 'About', about_path %></li>
			<li id="nav-sign-up"><a>Sign up</a></li>
			<li><a href="#">Login</a></li>
		</ul>
		<div id="menu-icon"></div>
	</div>
	
	 <%= yield %>
</div>


	

</body>
</html>

app/views/signup/new.html.erb
<div class="login">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>

    <%= form_for(@user) do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :placeholder => "First name" %>
      <%= f.label :last_name %>
      <%= f.text_field :last_name, :placeholder => "Last name" %>
      <%= f.label :email %>
      <%= f.email_field :email, :placeholder => "Email" %>
      <%= f.label :password %>
      <%= f.password_field :password, :placeholder => "Password" %>
      <%= f.submit "Create an account", class: "btn-submit" %>
    <% end %>

  
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.text_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Team</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.team_id %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Team:</strong>
  <%= @user.team_id %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/about.html.erb
<div id="content-container">
	<%= image_tag "soccer-background.jpg", alt: "Recruiter Image", id: "background-image" %>
	<div id="lets-talk">
		<table id="footer-menu">
			<tr>
				<td>Explore</td>
				<td>Clients</td>
				<td>Facebook</td>
				<td>News</td>
			</tr>
			<tr>
				<td>Culture</td>
				<td>Careers</td>
				<td>Twitter</td>
				<td>Contact</td>
			</tr>
			<tr>
				<td>Recruiting Rules</td>
				<td>Recruiting Events</td>
				<td>Instagram</td>
				<td></td>
			</tr>
		</table>
	</div>
</div>

app/views/welcome/index.html.erb
<div id="content-container">
<%= image_tag "background-coach.png", alt: "Recruiter Image", id: "background-image" %>
<div class="jumbotron">
	<div id="primary-content">
		<h1>Find the perfect NCAA program for you.</h1>
		<p>
		We help athletes find the NCAA program that suits them best based on financial, academic, and athletic needs.
	    </p>
	</div>
</div>


<div class="ladder" id="ladder-rung-1">
	<div class="ladder-content" id="ladder-content-1">
	<h1>Search through DI, DII, DIII, NAIA, and Juco Programs</h1>
	</div>
</div>
<div class="container-popup">
		<div class="popup">

		<div id="x-icon">
		<div id="x-icon-background"></div>
			<%= image_tag "delete.svg", alt: "x-icon image", id:"x-icon" %>
		</div>
			<%= image_tag "Signup.png", alt: "Recruiter Image", id: "signup-image" %>
		</div>
	</div>
</div>